web:
  build: .
  command: 'bash -c ''npm start'''
  working_dir: /app/user
  environment:
    PORT: 8080
    DATABASE_URL: 'postgres://postgres:@db:5432/postgres'
  ports:
    - '8080:8080'
  links:
    - db
db:
  image: mongo
